macro(AddCoinbill_Lib Libname)
    include_directories(${COINBILL_TARGET_INCLUDE_DIRS} ${COINBILL_INC_DIR})
    add_definitions(${COINBILL_TARGET_DEFINES})
    link_directories(${COINBILL_TARGET_LIBRARY_DIRS})
    add_library(${Libname} STATIC ${ARGN})
    target_link_libraries(${Libname} ${COINBILL_TARGET_LIBRARIES})
endmacro()

macro(AddCoinbill_Exe ExeName)
    include_directories(${COINBILL_TARGET_INCLUDE_DIRS} ${COINBILL_INC_DIR})
    add_definitions(${COINBILL_TARGET_DEFINES})
    link_directories(${COINBILL_TARGET_LIBRARY_DIRS})
    add_executable(${ExeName} ${ARGN})
    target_link_libraries(${ExeName} ${COINBILL_TARGET_LIBRARIES})
endmacro()